' convert it with additional command line argument -DRELATIVE_INCLUDE="relative/absolute" to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include ./C4.puml
!else
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!endif

!define COMMENT(x) <i><color:grey>x</color></i>

hide circle
hide empty methods

' $getLink($link) - тут нужно разобраться...

!unquoted procedure Class($alias, $label="", $descr="", $tags="", $link="")
    class "$label" as $alias {
        COMMENT($breakText($descr, "\n"))
    }
!endprocedure